Status tracking mechanism
nimbal/nwpipeline pull request #26
Opened 2021-05-13 21:21 UTC by matthewwong525

Closes #7

2021-05-13 21:27 UTC, matthewwong525 commented
Accidentally branched off wrong branch so there's an extra commit, wait until we merge #26

2021-05-18 00:52 UTC, kitbeyer approved these changes

2021-05-18 01:21 UTC, kitbeyer requested changes
I really didn't know how this would work when I first started thinking about this but I really like the way you did this as a starting point. Only one thing I would change for now, can we use the True/False return of the function as Success/Fail in the status.csv and add an Error value or something if an exception arises instead of raising an exception whenever we want to say the function failed. I would like to differentiate between failure where we know why and failure where it raised an exception if possible.

2021-05-18 10:23 UTC, kitbeyer commented
I am going to modify any warnings in the other methods where the function exits to raise an exception instead like you have done for gait.

2021-05-19 14:11 UTC, merged