Integrate nwsleep into pipeline
nimbal/nwpipeline pull request #35
Opened 2021-05-17 17:35 UTC by matthewwong525

Closes #12

2021-05-18 01:32 UTC, kitbeyer commented
Do we really run sleep separately for each device? I don't think this way will work because not all devices have / will have 
accelerometers

2021-05-19 18:34 UTC, matthewwong525 commented
> Do we really run sleep separately for each device? I don't think this way will work because not all devices have / will have
> accelerometers

fixed!

2021-05-20 10:32 UTC, kitbeyer commented on nwpipeline/NWPipeline.py
> +        if single_stage in [None, 'nonwear', 'sleep']:
```suggestion
        if single_stage in [None, 'nonwear']:
```

2021-05-20 10:33 UTC, kitbeyer commented on nwpipeline/NWPipeline.py
>          if single_stage == 'crop':
```suggestion
        if single_stage in ['crop', 'sleep']:
```

2021-05-20 10:34 UTC, kitbeyer commented on nwpipeline/NWPipeline.py
>          if single_stage == 'crop':
if single stage selected is sleep it should read the nonwear data that was previously detected and saved rather than re run the nonwear detection

2021-05-20 10:43 UTC, kitbeyer commented on nwpipeline/NWPipeline.py
> +            sleep_csv_name = '.'.join(['_'.join([device_file_base, "SLEEP"]), "csv"])
Can you generate the filename from the participant info like we do in gait and activity? Also can you make subfolder under sleep for this data (sleep_bouts or something like that)?

2021-05-20 10:43 UTC, kitbeyer requested changes
Made some inline comments and requests.

2021-05-26 12:41 UTC, kitbeyer approved these changes

2021-05-26 12:42 UTC, closed without merging

2021-05-26 12:42 UTC, kitbeyer commented
Significant work on nwsleep required