Resolve issues in 0.4.0
nimbal/nwpipeline pull request #40
Opened 2021-05-21 00:31 UTC by matthewwong525

Closes #39 
Closes #30 
Closes #31

2021-05-25 15:23 UTC, kitbeyer requested changes
GAIT_BOUTS.csv output should only include:

study_code,subject_id,coll_id,gait_bout_num,start_timestamp,end_timestamp

- the data points are not needed, only start and end timestamps
- length can be calculated
- extra date not needed

2021-05-25 15:23 UTC, kitbeyer commented on nwpipeline/NWPipeline.py
> +            bouts_csv_path = os.path.join(self.dirs['gait_steps'], bouts_csv_name)
```suggestion
            bouts_csv_path = os.path.join(self.dirs['gait_bouts'], bouts_csv_name)
```

2021-05-25 15:23 UTC, kitbeyer commented on nwpipeline/NWPipeline.py
> +            steps_csv_path = os.path.join(self.dirs['gait_bouts'], steps_csv_name)
```suggestion
            steps_csv_path = os.path.join(self.dirs['gait_steps'], steps_csv_name)
```

2021-05-26 12:57 UTC, matthewwong525 commented on nwpipeline/NWPipeline.py
> +    def daily_gait(bout_times):
I was thinking it would be added to the feedback form scripts because the outputs are relevant to the feedback forms. For me it makes sense to put the post processing outside of the gait/bout processing. What are your thoughts?

2021-05-26 21:58 UTC, kitbeyer reviewed
Some inline comments

2021-05-27 19:33 UTC, kitbeyer approved these changes

2021-05-27 19:36 UTC, merged